# Generated by Django 3.2 on 2021-12-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_google_mainphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='google',
            name='main_pic',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='google',
            name='wiki',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
