# Generated by Django 3.2 on 2021-12-26 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_write'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='google',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.google'),
            preserve_default=False,
        ),
    ]
