# Generated by Django 3.2 on 2021-12-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_write_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='contents',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
