# Generated by Django 3.2 on 2021-12-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_write_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
