# Generated by Django 3.2 on 2021-12-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_write_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
