# Generated by Django 3.2 on 2021-12-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211227_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='url',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
