# Generated by Django 3.2 on 2021-12-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_write_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write',
            name='content',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
