# Generated by Django 3.2 on 2022-03-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='google',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='google',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='google',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
