# Generated by Django 3.2 on 2022-03-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220302_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='google',
            name='filtering',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
