# Generated by Django 3.2 on 2022-03-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_google_filtering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='google',
            name='filtering',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
