# Generated by Django 3.2 on 2022-03-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_google_mainphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='google',
            name='charge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='google',
            name='inout',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
