# Generated by Django 3.2 on 2022-03-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20220310_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='google',
            name='popular',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
