# Generated by Django 3.2 on 2022-03-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_google_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='google',
            name='theme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
